export enum ProCatSubTypes{
    ADD_UPDATE_FETCH = "ADD_UPDATE_FETCH",
    ADDING_UPDATING_FETCHING = "ADDING_UPDATING_FETCHING",
    DELETE = "DELETE",
    DELETING = "DELETING",
    FETCH_ALL = "FETCH_ALL",
    FETCHING_ALL = "FETCHING_ALL"
}